### ISSUE TITLE
Код на сайте не установлен

### ISSUE THREAD

**Issue by MilaFabio** [sape-ru/client-code-wordpress#2]
впервые пытаюсь добавить сайт в sape.ru и получаю 

> Код на сайте не установлен

а также появляется поле: URL страницы с кодом:

http://joxi.ru/DmB89XgcJvKE6A

**Comment by blurayman** [comment]
Добрый день,

мы не оказываем техническую поддержку через GitHub.

Чтобы мы могли лучше разобраться в проблеме, пожалуйста, отправьте
баг-репорт через свой аккаунт в sape.ru, указав

Url сайта
Версию Wordpress
Версию нашего плагина, котоая установлена в Wordpress
Настройки плагина, которые применяете

Отправить баг-репорт можно со страницы обратной связи на  help.sape.ru
(требуется авторизация)

https://help.sape.ru/sape/faq/1757


вс, 2 июн. 2019 г., 2:11 MilaFabio <notifications@github.com>:
